---
title: "Example"
author: "Aaron Peikert"
date: "2/12/2019"
output:
  html_document: default
  pdf_document:
    template: standard.tex
    extra_dependencies: #may clash with template, if you specify here something that is allready in template it fails
      lmodern: null
params:
  solution: TRUE
  code: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = params$code)
options(knitr.duplicate.label = 'allow') # workauround for purl see: https://stackoverflow.com/questions/36868287/
```

```{r packages, include=FALSE}
if(!require("pacman"))install.packages("pacman")
pacman::p_load("pander")
```

# SEM

1. Should you run trust that the default SEM-Options in `MPLUS` or `lavaan` are what I have in Mind?

```{asis, echo = params$solution}
Answer: NO!
```

# Cars

Fit a regession on mtcars. Report the main statistics. Convert one of the t-Values to F-Values.

```{r, include=params$code, results='hide'}
fit <- lm(mpg ~ hp + wt, data = mtcars)
```

```{r, echo=FALSE, results=ifelse(isTRUE(params$solution), "asis", "hide")}
pander(summary(fit))
```

```{r, include=params$solution, results='asis', echo=FALSE}
cat("The F-Value of the t-Value of the intercept is: ", round(fit$coefficients[[1]]^2, 2), ". This results from squaring the t-Value.")
```

```{r generate pure r script, include=FALSE}
input <- knitr::current_input(dir = TRUE)  # filename of input document
output <- paste(tools::file_path_sans_ext(input), 'R', sep = '.')
knitr::purl(input, output, documentation=0L, quiet=T)
```
